[alembic]
script_location = migrations
file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s
prepend_sys_path = .
sqlalchemy.url = postgresql://peblo_admin:peblo_secret_pass@localhost:5432/peblo_tv_db

[post_write_hooks]

[logging]
default_level = INFO
